# Vault Configuration Example

storage_path = "~/.vault/vault.db"
tenant_id = "acme-corp"

[cloud_sync]
backend = "S3"  # or "Postgres"
region = "us-east-1"
bucket = "vault-sync-bucket"
# database_url = "postgresql://user:pass@localhost/vault"

# AWS Configuration (optional)
# aws_access_key_id = "your-access-key"
# aws_secret_access_key = "your-secret-key"
# aws_region = "us-east-1"

# KMS Configuration (optional)
# kms_key_id = "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"